import type { Metadata } from "next";
import "./globals.css";

import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';

export const metadata: Metadata = {
  title: "Toph",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (

     <html lang="en">
        <PrimeReactProvider>
            <body>
                {children}
            </body>
        </PrimeReactProvider>
    </html>
  );
}
